#! /bin/bash

source /etc/default/snapshots

SUBPATH=".daily-$(date +%Y-%m-%d)"

if [ $# -gt 1 ]; then
    echo "usage: snapshots-mount [SUBPATH]"
    exit 2
fi

[ $# -eq 1 ] && SUBPATH=$1

# Check on distant folder and local mountpoint
if ! ssh ${SNAPSHOTS_USER}@${SNAPSHOTS_SERVER} test -e ${SNAPSHOTS_PATH}/${SUBPATH}; then
    echo "Error: remote folder ${SNAPSHOTS_PATH}/${SUBPATH} does not exist"
    exit 3
fi

MOUNTPOINT=$(mktemp -d /tmp/snapshot.XXX)
mount ${SNAPSHOTS_SERVER}:${SNAPSHOTS_PATH}/${SUBPATH} ${MOUNTPOINT}

echo "Snapshot ${SUBPATH} mounted in ${MOUNTPOINT}"
echo "Press Enter to umount and remove temporary directory"
read confirmation
umount ${MOUNTPOINT}
rmdir ${MOUNTPOINT}
