---

- name: Ensure snapshots user exist
  user:
    name: "{{ snapshots_user }}"
    state: present

- name: Ensure snapshot path exists
  file:
    path: "{{ snapshots_path }}"
    owner: "{{ snapshots_user }}"
    group: "{{ snapshots_user }}"
    state: directory

- name: Ensure snapshots path is in a btrfs volume
  shell: "test $(findmnt -n -o FSTYPE --target {{ snapshots_path }}) = 'btrfs'"
  check_mode: no
  changed_when: false

- name: Sudoers rights on btrfs
  copy:
    src: etc/sudoers.d/snapshots
    dest: /etc/sudoers.d/snapshots

- name: Copy snapshots-rsync script
  copy:
    src: usr/local/bin/snapshots-rsync
    dest: /usr/local/bin/snapshots-rsync
    mode: 0755

- name: Add snapshots-rsync service file
  copy:
    src: etc/systemd/system/snapshots-rsync.service
    dest: /etc/systemd/system/snapshots-rsync.service

- name: Create snapshots-rsync timer file
  template:
    src: etc/systemd/system/snapshots-rsync.timer.j2
    dest: /etc/systemd/system/snapshots-rsync.timer
  when: snapshots_rsync_calendar is defined

- name: Start and enable snapshots-rsync timer
  service:
    name: snapshots-rsync.timer
    state: started
    enabled: yes
    daemon_reload: yes
  when: snapshots_rsync_calendar is defined

- name: Ensure log directory exists
  file:
    path: /var/log/snapshots/
    owner: "{{ snapshots_user }}"
    group: "{{ snapshots_user }}"
    state: directory

- name: Create logrotate file
  copy:
    src: etc/logrotate.d/snapshots
    dest: /etc/logrotate.d/snapshots
